services:
  - type: web
    name: streambattle
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: db
      mountPath: /opt/render/project/src/db
      sizeGB: 1
